# vim:ft=ansible:
---
- name: Create letsencrypt config file /opt/letsencrypt/cli.ini
  template: 
    src: letsencrypt/cli.ini.j2
    dest: /opt/letsencrypt/cli.ini

- name: Let https through firewall (RHEL 7)
  firewalld:
    service: https
    permanent: true
    state: enabled
    immediate: true
  when: (ansible_distribution == "RedHat" and ansible_distribution_major_version == "7")

- name: Let http through firewall (RHEL 7)
  firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: true
  when: (ansible_distribution == "RedHat" and ansible_distribution_major_version == "7")

- name: Stop and disable iptables (RHEL 6)
  service:
    name: iptables
    state: stopped
    enabled: no
  when: (ansible_distribution == "RedHat" and ansible_distribution_major_version == "6")

- name: Check to see if SSL cert is already there
  stat:
    path: /etc/letsencrypt/live/{{ ansible_fqdn }}/fullchain.pem
  register: cert_present

- name: Stop nginx for letsencrypt
  service:
    name: nginx
    state: stopped
  when: cert_present.stat.exists == false

- name: Get SSL certificate from letsencrypt
  command: /opt/letsencrypt/letsencrypt-auto certonly -c /opt/letsencrypt/cli.ini --agree-tos --staging
  args:
    creates: /etc/letsencrypt/live/{{ ansible_fqdn }}/fullchain.pem
  notify: restart nginx
