---
- name: Load distro-specific vars
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"

- include_tasks: nginx.yml

- include_tasks: postgres.yml

- name: 'Download binary from https://releases.mattermost.org'
  get_url: 
    url: 'https://releases.mattermost.com/{{ mattermost_version }}/mattermost-team-{{ mattermost_version }}-linux-amd64.tar.gz'
    dest: /tmp/
  when: use_get_url

- name: Download binary from MatterMost website (using wget because get_url fails if system python is older than 2.7.5)
  command: "wget https://releases.mattermost.com/{{ mattermost_version }}/mattermost-team-{{ mattermost_version }}-linux-amd64.tar.gz"
  args:        
    chdir: /tmp/
    creates: /tmp/mattermost-team-{{ mattermost_version }}-linux-amd64.tar.gz
    warn: false
  when: not use_get_url

- name: Unpack mattermost archive.
  unarchive: 
    src: /tmp/mattermost-team-{{ mattermost_version }}-linux-amd64.tar.gz 
    dest: /opt/
    copy: no
  args:
    creates: /opt/mattermost/bin/platform

#- name: Edit /opt/mattermost/config/config.json
#  lineinfile:
#    dest: /opt/mattermost/config/config.json
#    regexp: '"DriverName": "mysql",'
#    line: '        "DriverName": "postgres",'
#    backrefs: yes

#- name: Edit /opt/mattermost/config/config.json
#  lineinfile:
#    dest: /opt/mattermost/config/config.json
#    regexp: '"DataSource":'
#    line: '        "DataSource": "postgres://{{ db_user }}:{{ db_password }}@127.0.0.1:5432/{{ db_name }}?sslmode=disable&connect_timeout=10",'
#    backrefs: yes 

- name: Create user to run mattermost service.
  user: 
    name: "{{ mattermost_user }}"
    system: yes
    createhome: no        

- name: Apply mattermost config.json template
  template:
    src: mattermost-config.json.j2
    dest: /opt/mattermost/config/config.json
    owner: "{{ mattermost_user }}"
    group: "{{ mattermost_user }}"
    mode: 0644
  
- name: Change mattermost directory permissions
  file:
    path: /opt/mattermost
    state: directory
    owner: "{{ mattermost_user }}"
    group: "{{ mattermost_user }}"
    recurse: yes

- include_tasks: "init/{{ init_system }}.yml"
 
- include_tasks: selinux.yml
  when: selinux_enable
  notify: restart nginx

- name: Enable Mattermost service
  service:
    name: mattermost
    enabled: yes
    state: started 


# vim:ft=ansible:
