---
- name: Copy nginx config file
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644

- name: Ensure nginx default configuration files are deleted
  file: 
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/nginx/conf.d/default.conf"
    - "/etc/nginx/conf.d/ssl.conf"
    - "/etc/nginx/conf.d/virtual.conf"
    - "/etc/nginx/sites-available"
    - "/etc/nginx/sites-enabled"

- include_tasks: "SSL/{{ SSL_type }}.yml"
  when: SSL_type != "nossl"

- name: Apply nginx config template for selected SSL type
  template:
    src: "nginx/{{ SSL_type }}-mattermost.conf.j2"
    dest: /etc/nginx/conf.d/mattermost.conf
  notify: restart nginx
# vim:ft=ansible
